# Generated by Django 3.2.7 on 2021-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('artist', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
