# Generated by Django 3.2.7 on 2021-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='artwork',
        ),
        migrations.AddField(
            model_name='gallery',
            name='artwork',
            field=models.ManyToManyField(to='main_app.Artwork'),
        ),
    ]
