# Generated by Django 3.2.7 on 2021-12-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211230_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.gallery')),
            ],
        ),
    ]
