# Generated by Django 3.2.7 on 2021-12-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='comments',
        ),
    ]
