# Generated by Django 3.2.7 on 2021-12-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_gallery_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gallery')),
            ],
        ),
    ]
