# Generated by Django 4.0 on 2022-01-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220103_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Search',
        ),
    ]
