# Generated by Django 4.0 on 2022-01-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_art_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='title',
            new_name='q',
        ),
    ]
