# Generated by Django 4.0 on 2022-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_title_search_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.TextField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
