# Generated by Django 4.0 on 2022-01-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_art_delete_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='art',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
