# Generated by Django 4.0 on 2022-01-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_art_artist_alter_art_country_alter_art_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='art',
            field=models.ManyToManyField(to='main_app.Art'),
        ),
    ]
